
### train_pose2rot.yaml ###
name: Pose2Rot training

runtime:
  device: cuda
  seed: 42
  debug: false

output:
  checkpoint_root: ./checkpoints/pose2rot


experiment:
  exp: exp_pose2rot_v3

model:
  target: models.v2.pose2rot.model.Pose2RotMemoryRestModel
  params:
    q_dim: 256
    rest_layers: 4
    pose_layers: 4
    memory_layers: 4
    decoder_layers: 10
    num_heads: 8
    joint_embed_dim: 768
    temporal_window: 2
    temporal_dropout: 0.1
    decoder_cond_mode: add # add | concat
    pose_rest_film: true
    memory_rest_film: true
    decoder_rest_film: true
    pose_use_graph: true
    use_grad_checkpoint: false
    decoder_use_cross_layers: 6

train:
  batch_size: 1
  epochs: 500
  grad_accum_steps: 1
  lr: 0.0001
  max_ckpt: 100
  num_workers_train: 2
  test_every: 1
  pretrain_ckpt: null

  loss:
    rot_loss_type: smooth_l1
    vel_loss_type: smooth_l1
    acc_loss_type: smooth_l1
  
  weight:
    root_wt: 0.1
    fk_wt: 0.0
    vel_wt: 1.0
    acc_wt: 0.0
    rot_wt: 1.0

  vis_every: 5
  weight_decay: 0.0

eval:
  batch_size: 1
  num_workers: 2

data:
  seq_len: 48
  bvh_dir: datasets/zoo1030/bvh
  cache_scale: true
  limit_species_debug: []
  mmap: true
  split_json: datasets/zoo1030/selected_test_split1010.json
  train_memory_pkl_path: datasets/zoo1030/cache/species_fps_memory_yAll/fps_select_by_rot_32.pkl
  test_memory_pkl_path: datasets/zoo1030/cache/species_fps_memory_yAll/fps_select_by_rot_32.pkl
