
### train_video2pose.yaml ###
name: "Video2Pose training"

runtime:
  device: "cuda"
  seed: 42
  debug: false

output:
  checkpoint_root: "./checkpoints/video2pose"

experiment:
  exp: "exp2503"

model:
  target: "models.v2.video2pose.model.RefGuidedVideo2PoseModel"

  params:
    q_dim: 256
    num_layers: 12
    num_heads: 8
    ref_layers: 4
    img_dim: 1024
    num_joints: 150

    use_graph_ref_outer: false
    use_graph_ref_inner: true
    use_graph_temporal_outer: false
    use_graph_temporal_inner: true
    use_joint_embed: true

  attention_kwargs:
    seq_len: 24
    selfatt_temporal_layer_flag: []
    selfatt_temporal: true
    crossatt2_temporal: true
    selfatt_slidwindow: 5
    crossatt2_slidwindow: 5

data:
  bvh_dir: "datasets/zoo1030/bvh"
  split_json: "datasets/zoo1030/selected_test_split1010.json"
  mmap: true
  cache_scale: true
  limit_species_debug: []
  train_memory_pkl_path: datasets/zoo1030/cache/species_fps_memory_yAll/fps_select_by_rot_32.pkl
  test_memory_pkl_path: datasets/zoo1030/cache/species_fps_memory_yAll/fps_select_by_rot_32.pkl

train:
  epochs: 500
  batch_size: 1
  num_workers_train: 4

  lr: 0.0001
  weight_decay: 0.0
  loss_type: "l2"

  grad_accum_steps: 4
  test_every: 1
  vis_every: 5
  max_ckpt: 5
  pretrain_ckpt: null

eval:
  batch_size: 1
  num_workers: 2
  preload_all: false
  split_groups: ["seen", "rare", "unseen"]
  best_metric_split: "seen"
  best_metric_name: "mpjpe"
